name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]


jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: run
      run: |
        sh run.sh
      env:
          PUSH_GROUP: ${{ secrets.PUSH_GROUP }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
          PUSH_ON: ${{ secrets.PUSH_ON }}
